# -*- coding: utf-8 -*-
"""TE_UTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124ROBagQup-emyRcR8Nxvb0EqYcoQZIA
"""

# ============================================
# SETUP ENVIRONMENT
# ============================================

!pip install -q ultralytics roboflow

from ultralytics import YOLO
import os

print("✅ Setup selesai")

# ============================================
# DOWNLOAD DATASET ROBOFLOW
# ============================================

from roboflow import Roboflow

API_KEY = "K2Seav9Wxp3HQyG9kCCi"  # ← WAJIB DIISI

rf = Roboflow(api_key=API_KEY)

project = rf.workspace("indonesia-rupiah-currency-dataset").project("indonesia-rupiah-detection")
dataset = project.version(3).download("yolov8")

print("📦 Dataset di:", dataset.location)

# ============================================
# TRAINING YOLOv8
# ============================================

model = YOLO("yolov8n.pt")  # model ringan (cepat)

model.train(
    data=f"{dataset.location}/data.yaml",
    epochs=10,        # bisa ganti 5 kalau buru-buru
    imgsz=640,
    batch=16,
    device=0          # pakai GPU
)

print("✅ Training selesai")

# ============================================
# LIHAT HASIL MODEL
# ============================================

!ls runs/detect/train/weights

# ============================================
# UPLOAD GAMBAR TEST
# ============================================

from google.colab import files
uploaded = files.upload()

# ============================================
# TEST DETECTION
# ============================================

model = YOLO("runs/detect/train/weights/best.pt")

results = model.predict(source=list(uploaded.keys())[0], save=True)

print("✅ Detection selesai, hasil disimpan di folder runs/")

# ============================================
# TAMPILKAN HASIL GAMBAR
# ============================================

import glob
from IPython.display import Image, display

images = glob.glob("runs/detect/predict/*.jpg")

for img in images:
    display(Image(filename=img))

# ============================================
# DOWNLOAD MODEL BEST
# ============================================

from google.colab import files

files.download("runs/detect/train/weights/best.pt")